### ISSUE TITLE
High ram utilization

### ISSUE THREAD

**Issue by marcellov7** [Pixboost/transformimgs#51] opened 2024-07-25 22:29 UTC
Hi, thanks for your contribution!

When I set the cache to 0, the system keeps keeping the memory full. What I want to achieve, considering that we use Cloudflare as a cache in front of the service, is to avoid storing images or otherwise always free up the available RAM memory. Once processed, these images will be available through the Cloudflare cache, so we do not need to keep storing. Our goal is to optimize and reduce these spikes in deployment.

Is there a solution to this?

Thank you

![image](https://github.com/user-attachments/assets/8ba6cf02-98c6-4b85-8d54-d4d514bcf3c5)

**Comment by dooman87** [comment] 2024-07-26 10:53
Hi there,

Unfortunately, the `cache` option wouldn't help here as it only controls HTTP header in the response, so you probably wouldn't want to set it to 0, so Cloudflare can still recognize response as cacheable.

We don't have any cache in the application, so the memory spikes would usually mean that that your server can't keep up with the load. That's happening due to when request is coming to the server the application will download a **source image into the memory** and sends it to the processor queue. There are several processors that are working in parallel (`proc` option that defaults to number of processors).

Couple of questions I have:

* What version of the application are you using?
* Do you see the response time is growing when spikes are happening?
* Does the process get killed by the OS cause there is no memory?


Couple of things I would recommend:

* Check that `cache` parameter is not 0 and CloudFlare is caching the images
* Try to use more powerful machine or with more cores - image processing is CPU hungry
* Setting `MAGICK_TIME_LIMIT` to something sensible to make sure there is no transformations that take long and blocking the queues. Could be 5 or 10 seconds?

Something we could do on our side is probably limit the amount of downloaded images we store and reject further requests (send `429 Too Many Requests`) when it reaches threshold. 

Let me know how you go and we can look into this further.

**Comment by marcellov7** [comment] 2024-07-26 12:48
Hi,
Thanks for your suggestions!

- What version of the application are you using?
latest
- Do you see the response time is growing when spikes are happening?
No
- Does the process get killed by the OS cause there is no memory?
Yes

the only really important thing is that it's actually true with Cloudflare that if it gets 0 it won't cach the content, 
but we've created a custom rule that allows Cloudflare to cache the contents by ignoring the source cacheTTL.

So we were wondering if it would be possible to override the caching of images, so that we could leave the dirty work of caching to Cloudflare and keep the image process server pretty light at all times.

Thanks

**Comment by dooman87** [comment] 2024-07-27 10:40
Thanks a lot for all the info and background!

The one thing I worry about is growing memory footprint when nothing is happening. 

Let me run performance tests and see if there is no memory leaks around. I will also run remove in-memory cache of source images and run the tests again to see how memory footprint is doing. 

We do use the same version of this library to run SaaS offering and using the latest version and its been quite stable from memory prospective. But we horizontally scale it base on the load.

One last question, do you use the docker image to run the service?

**Comment by marcellov7** [comment] 2024-07-27 10:59
You're welcome, actually thank you for the fantastic work.

I used both this template 
https://railway.app/template/a_Rgxz
It seems to me that I'm fishing from the latest version of Docker Hub.

I also always tried with Railway taking the project from git, but it seems to me that it does the same thing using docker.

If I can help further let me know,

**Comment by dooman87** [comment] 2024-07-27 11:36
Thanks for the prompt reply!

Prob one last question that will help me to get on the right track. Are you source images are mostly PNGs or JPEGs? Or mix of both?

**Comment by marcellov7** [comment] 2024-07-27 11:41
Really mixed, but they're also already pre-compressed a little bit. I don't know if it can be useful, I can invite you to Railway (if it can be done) on the instance that is currently without traffic.
Anything to be helpful. Thank you

**Comment by dooman87** [comment] 2024-07-28 12:14
I was able to reproduce the problem and got something going for the fix here: https://github.com/Pixboost/transformimgs/pull/52. The PR is almost ready codewise, but we'd need to do it a bit more testing to release it. I could push the image to Docker hub if you'd like to test it as well and see if it's fixing the problem?

The problem is `imagick` library which is caching things and eats as much memory as it needs. For instance, on my local machine when I run performance test the memory grows to 2.5Gb then just stays at that level no matter how many times i run the test. That scenario above is working well when you have dedicated instance for `transformimgs` but obviously is not working well when it's shared or constrained environment.

**Comment by marcellov7** [comment] 2024-07-28 12:55
Ok I'll try it directly from the branch, I'll let you know. Thanks in the meantime.

**Comment by dooman87** [comment] 2024-08-04 11:28
Alright, I tested that one and the memory consumption never crossed 1Gb for me. There is a slight (+3%) increase in latency but gain in the memory usage worth it. Closing this one for now, but happy to re-open if the problem still exist.

**Closed by dooman87** 2024-08-04 11:28 UTC
